import React from "react";

import "./tracking.styles.scss";

const TrackingPage = () => (
  <div className="tracking-page">
    <div className="container px-1 px-md-4 py-5 mx-auto tracking-body">
      <div className="card">
        <div className="row d-flex justify-content-between px-3 top">
          <div className="d-flex">
            <h5>
              ORDER <span className="text-primary font-weight-bold">#6152</span>
            </h5>
          </div>
          <div className="d-flex flex-column text-sm-right">
            <p className="mb-0">
              Expected Arrival <span>01/06/20</span>
            </p>
            <p>
              Grasshoppers{" "}
              <span className="font-weight-bold">
                <a href="https://www.grasshoppers.lk/customers/action/track/V534HB">
                  V534HB
                </a>
              </span>
            </p>
          </div>
        </div>{" "}
        {/* Add class 'active' to progress */}
        <div className="row d-flex justify-content-center">
          <div className="col-12">
            <ul id="progressbar" className="text-center">
              <li className="active step0" />
              <li className="active step0" />
              <li className="active step0" />
              <li className="step0" />
              <li className="step0" />
            </ul>
          </div>
        </div>
        <div className="row justify-content-between top">
          <div className="row d-flex icon-content">
            {" "}
            <img className="icon" src="https://i.imgur.com/9nnc9Et.png" />
            <div className="d-flex flex-column">
              <p className="font-weight-bold">
                Order
                <br />
                Processed
              </p>
            </div>
          </div>
          <div className="row d-flex icon-content">
            {" "}
            <img className="icon" src="https://i.imgur.com/GiWFtVu.png" />
            <div className="d-flex flex-column">
              <p className="font-weight-bold">
                Order
                <br />
                Designing
              </p>
            </div>
          </div>
          <div className="row d-flex icon-content">
            {" "}
            <img className="icon" src="https://i.imgur.com/u1AzR7w.png" />
            <div className="d-flex flex-column">
              <p className="font-weight-bold">
                Order
                <br />
                Shipped
              </p>
            </div>
          </div>
          <div className="row d-flex icon-content">
            {" "}
            <img className="icon" src="https://i.imgur.com/TkPm63y.png" />
            <div className="d-flex flex-column">
              <p className="font-weight-bold">
                Order
                <br />
                En Route
              </p>
            </div>
          </div>
          <div className="row d-flex icon-content">
            {" "}
            <img className="icon" src="https://i.imgur.com/HdsziHP.png" />
            <div className="d-flex flex-column">
              <p className="font-weight-bold">
                Order
                <br />
                Arrived
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="card">
        <div className="row d-flex justify-content-between px-3 top">
          <div className="d-flex">
            <h6>
              <span className="text-primary font-weight-bold">
                2020-05-27 11:26:08 AM{" "}
              </span>
              REQUEST CREATED
            </h6>
          </div>
        </div>
        <div className="row d-flex justify-content-between px-3 top">
          <div className="d-flex">
            <h6>
              <span className="text-primary font-weight-bold">
                2020-06-04 06:59:48 AM{" "}
              </span>
              ATTEMPT 1 COMPLETED. ~ ***[AUTO GENERATED BY GRASSHOPPERS]***
            </h6>
          </div>
        </div>
        <div className="row d-flex justify-content-between px-3 top">
          <div className="d-flex">
            <h6>
              <span className="text-primary font-weight-bold">
                2020-06-04 06:59:48 AM{" "}
              </span>
              RETURN TO VENDOR RECORD CREATED ~ RC806_118{" "}
            </h6>
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default TrackingPage;
